name: add_build_to_release

on:
  release:
    types: [ "created" ]

env:
  BUILD_PROJECT: "SpaceShooter2"
  PUBLISH_ARCHITECTURES: "linux-x64 win-x64"

jobs:
  add_build_to_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: publish linux-x64
      run: dotnet publish SpaceShooter2 -c Release -r linux-x64

    - name: publish win-x64
      run: dotnet publish SpaceShooter2 -c Release -r linux-x64

    - name: publish and compress architectures
      run: |
        [ ! -d "${{github.workspace}}/builds" ] && mkdir "${{github.workspace}}/builds"
        for arch in ${{env.PUBLISH_ARCHITECTURES}}; do
            dotnet publish ${{env.BUILD_PROJECT}} -c Release -r "$arch"
            cd "${{env.BUILD_PROJECT}}/bin/Release/net6.0/$arch"
            zip "${{github.workspace}}/builds/$arch_${{env.BUILD_PROJECT}}.zip" *
            cd -
        done

    - name: upload release assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.release.tag_name}}
        files: "${{github.workspace}}/builds/*.zip"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

