name: add_build_to_release

on:
  release:
    types: [ "created" ]

env:
  BUILD_PROJECT: "SpaceShooter2"

jobs:
  add_build_to_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build_project
      with:
        project-name: "${{env.BUILD_PROJECT}}"

    - name: compress build files
      run: zip "$BUILD_PROJECT_win-64.zip" "${{env.BUILD_PROJECT}}/bin/Release/net6.0/*" -r

    - name: upload release assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.release.tag_name}}
        files: "./${{env.BUILD_PROJECT}}_win-64.zip"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

