name: add_build_to_release

on:
  release:
    types: [ "created" ]

env:
  BUILD_PROJECT: "SpaceShooter2"
  PUBLISH_ARCHITECTURES: "linux-x64 win-x64"
  PRODUCED_FILES: ""

jobs:
  add_build_to_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: publish and compress architectures
      run: |
        [ ! -d "${{github.workspace}}/builds" ] && mkdir "${{github.workspace}}/builds"
        for arch in ${{env.PUBLISH_ARCHITECTURES}}; do
            dotnet publish ${{env.BUILD_PROJECT}} -c Release --self-contained -r "$arch"

            fname="${{github.workspace}}/builds/$arch_${{env.BUILD_PROJECT}}.zip"
            PRODUCED_FILES="$fname ${{env.PRODUCED_FILES}}"

            cd "${{env.BUILD_PROJECT}}/bin/Release/net6.0/$arch"
            zip $fname *
            cd -
        done

    - name: upload release assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.release.tag_name}}
        files: "${{env.PRODUCED_FILES}}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

