name: verify_build_integrity

on:
  push:
    branches:  [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_PROJECT: "SpaceShooter2"

jobs:
  verify_build_integrity:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/build_project
